### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by git-shad0w** [Coders-HQ/CHQ_Frontend#1]
I'm not really sure if I did setup docker correctly, the container keeps running on a virtual network with IP
![Docker_Desktop_vZaoBemUte](https://user-images.githubusercontent.com/34681035/102357861-3cbd9a80-3fc8-11eb-910e-312d205b87f7.png)
 172.17.0.2

**Comment by ralsuwaidi** [comment]
can you post the dockerfile and run command?

**Comment by ralsuwaidi** [comment]
or push your workspace over here so we can see the file

**Comment by ralsuwaidi** [comment]
if it still doesn't work try `-p 0.0.0.0:33324:33324`

**Comment by git-shad0w** [comment]
lol nvm got it fixed.. I used docker desktop instead and I think docker wasn't getting binded to port 33324 in the host machine, because react dev server was listening on port 33324 but there was nothing getting binded to it.. 

until i added this.. (green rectangle)

![Docker_Desktop_gmqg436CY4](https://user-images.githubusercontent.com/34681035/102370544-9cbb3d80-3fd6-11eb-9ecc-9f313b51ca5a.png)

I'm still not sure why `docker run -d -p 0.0.0.0:33324:33324 chqfrontend:latest` wasn't working aswell, it was running the docker container then it stops suddenly, **but for now using docker desktop fixes it..**

### So apparently I was not running the docker container correctly lol..
